#!/usr/bin/env python3
"""Rank zero-side-data contexts for the causal SCR2 take decision."""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from pathlib import Path


def entropy_bits(takes: int, total: int) -> float:
    if takes == 0 or takes == total:
        return 0.0
    p = takes / total
    return -takes * math.log2(p) - (total - takes) * math.log2(1.0 - p)


def beta_code_bits(takes: int, total: int, yes: float, no: float) -> float:
    misses = total - takes
    log_probability = (
        math.lgamma(yes + takes)
        + math.lgamma(no + misses)
        - math.lgamma(yes + no + total)
        - math.lgamma(yes)
        - math.lgamma(no)
        + math.lgamma(yes + no)
    )
    return -log_probability / math.log(2.0)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stats", type=Path)
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--priors", type=Path,
                        help="optional C++ include with 8-bit global priors")
    parser.add_argument("--strength", type=float, default=32.0,
                        help="hierarchical context prior strength")
    args = parser.parse_args()

    rows: dict[str, list[tuple[int, int, int, int]]] = defaultdict(list)
    global_counts: dict[int, tuple[int, int]] = {}
    with args.stats.open(newline="", encoding="utf-8") as source:
        for row in csv.DictReader(source):
            pattern = int(row["pattern"])
            context = int(row["context"])
            triggers = int(row["triggers"])
            takes = int(row["takes"])
            kind = row["context_kind"]
            rows[kind].append((pattern, context, triggers, takes))
            if kind == "global":
                global_counts[pattern] = (triggers, takes)

    baseline_entropy = sum(
        entropy_bits(takes, triggers)
        for triggers, takes in global_counts.values()
    )
    baseline_laplace = sum(
        beta_code_bits(takes, triggers, 1.0, 1.0)
        for triggers, takes in global_counts.values()
    )

    results = []
    for kind, items in rows.items():
        empirical = sum(entropy_bits(takes, triggers)
                        for _, _, triggers, takes in items)
        laplace = sum(beta_code_bits(takes, triggers, 1.0, 1.0)
                      for _, _, triggers, takes in items)
        hierarchical = 0.0
        max_context = 0
        for pattern, context, triggers, takes in items:
            global_total, global_takes = global_counts[pattern]
            p = (global_takes + 1.0) / (global_total + 2.0)
            hierarchical += beta_code_bits(
                takes,
                triggers,
                1.0 + args.strength * p,
                1.0 + args.strength * (1.0 - p),
            )
            max_context = max(max_context, context)
        dense_bytes = 128 * (max_context + 1)
        results.append({
            "context_kind": kind,
            "active_cells": len(items),
            "dense_table_bytes": dense_bytes,
            "empirical_bits": empirical,
            "empirical_saving_bytes": (baseline_entropy - empirical) / 8.0,
            "laplace_bits": laplace,
            "laplace_delta_bytes": (baseline_laplace - laplace) / 8.0,
            "hierarchical_bits": hierarchical,
            "hierarchical_delta_bytes":
                (baseline_laplace - hierarchical) / 8.0,
        })
    results.sort(key=lambda item: item["hierarchical_delta_bytes"],
                 reverse=True)

    total_triggers = sum(value[0] for value in global_counts.values())
    total_takes = sum(value[1] for value in global_counts.values())
    report = {
        "patterns": len(global_counts),
        "triggers": total_triggers,
        "takes": total_takes,
        "baseline_pattern_entropy_bits": baseline_entropy,
        "baseline_pattern_laplace_bits": baseline_laplace,
        "hierarchical_prior_strength": args.strength,
        "contexts": results,
        "rule": (
            "Empirical savings are an oracle bound. Retain a context only "
            "after exact archive, S1-size and roundtrip gates."
        ),
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n",
                           encoding="utf-8")

    if args.priors:
        probabilities = [128]
        for pattern in range(1, 129):
            triggers, takes = global_counts.get(pattern, (0, 0))
            probability = round(255.0 * (takes + 1.0) / (triggers + 2.0))
            probabilities.append(max(1, min(254, probability)))
        lines = [
            "// Generated by tools/analyze_causal_scr2_contexts.py.",
            "inline constexpr std::uint8_t kCausalScr2GlobalPrior[129] = {",
        ]
        for begin in range(0, len(probabilities), 16):
            lines.append("  " + ", ".join(
                str(value) for value in probabilities[begin:begin + 16]) + ",")
        lines.append("};")
        args.priors.write_text("\n".join(lines) + "\n", encoding="ascii")

    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
