#!/usr/bin/env python3
"""Design a compact learned prior table for causal SCR2 decisions."""

from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path


PROBABILITY_CODES = (
    1, 2, 4, 8, 16, 32, 56, 88,
    128, 168, 200, 224, 240, 248, 252, 255,
)
PATTERN_COUNT = 128
CONTEXT_COUNT = 512


def beta_code_bits(takes: int, total: int, yes: float, no: float) -> float:
    misses = total - takes
    log_probability = (
        math.lgamma(yes + takes)
        + math.lgamma(no + misses)
        - math.lgamma(yes + no + total)
        - math.lgamma(yes)
        - math.lgamma(no)
        + math.lgamma(yes + no)
    )
    return -log_probability / math.log(2.0)


def prior_counts(code: int, strength: int) -> tuple[int, int]:
    interior = strength - 2
    yes = 1 + round(interior * PROBABILITY_CODES[code] / 256.0)
    yes = max(1, min(strength - 1, yes))
    return yes, strength - yes


def write_cpp(path: Path, strength: int, codes: list[int]) -> None:
    packed = []
    for index in range(0, len(codes), 2):
        low = codes[index]
        high = codes[index + 1] if index + 1 < len(codes) else 8
        packed.append(low | (high << 4))
    lines = [
        "// Generated by tools/design_causal_scr2_priors.py.",
        f"inline constexpr std::uint16_t kCausalScr2PriorStrength = {strength}u;",
        "inline constexpr std::uint8_t kCausalScr2PriorCodes[] = {",
    ]
    for begin in range(0, len(packed), 24):
        lines.append("  " + ", ".join(
            f"0x{value:02x}" for value in packed[begin:begin + 24]) + ",")
    lines.append("};")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("stats", type=Path)
    parser.add_argument("--context-kind", default="band64_line")
    parser.add_argument("--report", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--strengths", default="4,8,16,32,64,128")
    args = parser.parse_args()

    counts: dict[tuple[int, int], tuple[int, int]] = {}
    with args.stats.open(newline="", encoding="utf-8") as source:
        for row in csv.DictReader(source):
            if row["context_kind"] != args.context_kind:
                continue
            pattern = int(row["pattern"])
            context = int(row["context"])
            counts[(pattern, context)] = (
                int(row["triggers"]), int(row["takes"]))

    neutral_bits = sum(
        beta_code_bits(takes, total, 1.0, 1.0)
        for total, takes in counts.values()
    )
    trials = []
    best_codes: list[int] | None = None
    best_strength = 0
    best_bits = float("inf")
    for strength in (int(value) for value in args.strengths.split(",")):
        if strength < 3:
            raise ValueError("prior strength must be at least 3")
        table = [8] * ((PATTERN_COUNT + 1) * CONTEXT_COUNT)
        bits = 0.0
        histogram = [0] * len(PROBABILITY_CODES)
        for (pattern, context), (total, takes) in counts.items():
            candidates = []
            for code in range(len(PROBABILITY_CODES)):
                yes, no = prior_counts(code, strength)
                candidates.append(beta_code_bits(takes, total, yes, no))
            code = min(range(len(candidates)), key=candidates.__getitem__)
            table[pattern * CONTEXT_COUNT + context] = code
            histogram[code] += 1
            bits += candidates[code]
        trial = {
            "strength": strength,
            "coded_bits": bits,
            "saving_bytes_vs_neutral": (neutral_bits - bits) / 8.0,
            "code_histogram": histogram,
        }
        trials.append(trial)
        if bits < best_bits:
            best_bits = bits
            best_strength = strength
            best_codes = table

    assert best_codes is not None
    report = {
        "context_kind": args.context_kind,
        "active_cells": len(counts),
        "neutral_bits": neutral_bits,
        "dense_cells": len(best_codes),
        "packed_table_bytes": (len(best_codes) + 1) // 2,
        "probability_codes_256": list(PROBABILITY_CODES),
        "trials": trials,
        "best_strength": best_strength,
        "best_bits": best_bits,
        "best_saving_bytes_vs_neutral": (neutral_bits - best_bits) / 8.0,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2) + "\n",
                           encoding="utf-8")
    if args.output:
        write_cpp(args.output, best_strength, best_codes)
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
